Numpy libaray

In [3]:
import numpy as np

array_1 = np.array([3,4,5,6])
print(array_1)


[3 4 5 6]


In [3]:
import numpy as np

array_1 = np.array([3,4,5,6])
array_2 = np.array([2,3,4,5])
sum_array = array_1 + array_2
sub_array = array_2 - array_1
array = array_1 * array_2 
dev_array = array_2/ array_1
print(sum_array)
print(sub_array)
print(array)
print(dev_array)

[ 5  7  9 11]
[-1 -1 -1 -1]
[ 6 12 20 30]
[0.66666667 0.75       0.8        0.83333333]


In [5]:
import numpy as np

array_1 = np.array([3,4,5,6])
sq_array = np.square(array_1)
print(sq_array)

[ 9 16 25 36]


In [4]:
import numpy as np

array_1 = np.array([3,4,25,6])
sum_array = np.sum(array_1)
print(sum_array)

38


In [7]:
import numpy as np

array_1 = np.array([3,4,5,6])
mean_array = np.mean(array_1)
print(mean_array)

4.5


In [8]:
import numpy as np

array_1 = np.array([3,4,5,6])
max_array = np.max(array_1)
print(max_array)

6


In [9]:
import numpy as np

array_1 = np.array([3,4,5,6])
min_array = np.min(array_1)
print(min_array)

3


In [22]:
import numpy as np
array_1 = np.array([[1,2,3] , [4,5,6]])
print(array_1)
print(array_1.shape)
print(array_1.size)
print(array_1.ndim)
print(array_2.dtype)


[[1 2 3]
 [4 5 6]]
(2, 3)
6
2
int64


In [21]:
array_2 = np.array([[[1,2,3] , [4,5,6]] , [[7,8,9] , [3,7,1]] ])
print(array_2)
print(array_2.shape)
print(array_2.size)
print(array_2.ndim)
print(array_2.dtype)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 7 1]]]
(2, 2, 3)
12
3
int64


In [24]:
array = np.array([[1,2,3] , [2,5,6]])
print(array[1,1])

5


<!-- #create the numpy array with the shape four by 5 containing the numbers 1 to 20

# perfome the following oparation on the above mactriese
# * add 10 -to every element
# multipy every element by 2
# calculate the squre of each element -->

In [25]:
import numpy as np
array_1 = np.array([[1,2,3,7,8] , [4,5,6,2,1],[1,2,3,7,6] , [4,5,6,1,2],])
array_add_10 = array_1 + 10
print(array_add_10)
array_multi_ = array_1 * 2
print(array_multi_)
array_power = array_1 **2
print(array_power)


[[11 12 13 17 18]
 [14 15 16 12 11]
 [11 12 13 17 16]
 [14 15 16 11 12]]
[[ 2  4  6 14 16]
 [ 8 10 12  4  2]
 [ 2  4  6 14 12]
 [ 8 10 12  2  4]]
[[ 1  4  9 49 64]
 [16 25 36  4  1]
 [ 1  4  9 49 36]
 [16 25 36  1  4]]


In [28]:
arr = np.array([10,20,30,40,50])
condition = arr > 25
print(condition)
result = arr[condition]
print(result)

[False False  True  True  True]
[30 40 50]


In [29]:
arr = np.array([10,20,20,30,40,50])
filtered = arr[(arr>20) & (arr<50)]
print(filtered)

[30 40]


create a numpy array with nums 1 -20
use boolen indexing to extarct all even numbers

given the numpy array with elemnts 10 20 30 40 50 , use boolean indexing to extarct all elemnts greter than the mean of the array


In [33]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
filtered = arr[(arr % 2 == 0)]
print(filtered)


array = np.array([10,20,30,40,50])
mean_array = np.mean(array)

filtered_arr = array[array > mean_array]
print(filtered_arr)


[ 2  4  6  8 10 12 14 16 18 20]
[40 50]


In [34]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [40]:
print(np.zeros((2,3),dtype=int))

[[0 0 0]
 [0 0 0]]


In [41]:
print(np.full(8,10))

[10 10 10 10 10 10 10 10]


In [42]:
print(np.full((3,4) , 7))

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [44]:
print(np.empty((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


pandas library

In [54]:
import pandas as pd

data = {'Name' : ['sachi' , 'Bob' , 'vima'], 'Age' : [23,21,54]}

df = pd.DataFrame(data)
# print(df)
print(type(df))

# print(df.loc[1,'Name'])

# print(df.iloc[2,0])

# print(df.loc[2])

print(df.loc[[0,2]])

<class 'pandas.core.frame.DataFrame'>
    Name  Age
0  sachi   23
2   vima   54


In [68]:
import pandas as pd
data = {
    "calories" : [420,329,429],
    "duration" : [50,45,40]
}
df = pd.DataFrame(data, index=["day1","day2","day3"])

print(df)

print(df.loc["day3", "calories"])

print(df.iloc[2,0])

print(df.loc["day2"])

print(df.iloc[1])

print(df["calories"])




      calories  duration
day1       420        50
day2       329        45
day3       429        40
429
429
calories    329
duration     45
Name: day2, dtype: int64
calories    329
duration     45
Name: day2, dtype: int64
day1    420
day2    329
day3    429
Name: calories, dtype: int64


In [78]:
import pandas as pd
data = {
    "calories" : [420,329,429],
    "duration" : [50,45,40]
}

df = pd.DataFrame(data)
# print(df.shape)
# print(df.size)
# print(df.dtypes)

# print(df.columns)
# print(list(df.columns))

# array = df.values
# print(array)
# print(type(array))

print(len(df))

print(df.mean)
print(df.sum)

3
<bound method DataFrame.mean of    calories  duration
0       420        50
1       329        45
2       429        40>
<bound method DataFrame.sum of    calories  duration
0       420        50
1       329        45
2       429        40>


you are a data analitist for a company the company has provided with a following table contain sales data
task : 
use pandas to load the above table into a data frame 
add the new coloumn total_revenue that calculates the total revenune for the each order
identify the best selling product(s) 

In [90]:
import pandas as pd
data= {
    'OrderId':[101,102,103,104,105],
    'Product':['Laptop','SmartPhone','Desk Chair','Monitor','BookShelf'],
    'Category':['Electronic','Electronic','Electronic','Electronic','Furniture'],
    'Quantity':[2,5,10,4,2],
    'PricePerUnit':[1000,800,150,200,300]
}

df = pd.DataFrame(data)

df['TotalReneve'] = df['Quantity'] * df['PricePerUnit']
print(df)



high_revenue = df[df['TotalReneve'] == df['TotalReneve'].max()]
print(high_revenue)


   OrderId     Product    Category  Quantity  PricePerUnit  TotalReneve
0      101      Laptop  Electronic         2          1000         2000
1      102  SmartPhone  Electronic         5           800         4000
2      103  Desk Chair  Electronic        10           150         1500
3      104     Monitor  Electronic         4           200          800
4      105   BookShelf   Furniture         2           300          600
   OrderId     Product    Category  Quantity  PricePerUnit  TotalReneve
1      102  SmartPhone  Electronic         5           800         4000


In [92]:
data = {
    'Name': ['Alice','Bob','Charlie','David'],
    'Age' : [23,24,27,38],
    'Score' : [34,56,78,82]
}
df = pd.DataFrame(data)

filtered = df[df['Age'] >25]
print(filtered)
print(type(filtered))

sorted = df.sort_values(by='Age')
print(sorted)

df['salary'] = [2000,4000,3007,2990]
print(df)

      Name  Age  Score
2  Charlie   27     78
3    David   38     82
<class 'pandas.core.frame.DataFrame'>
      Name  Age  Score
0    Alice   23     34
1      Bob   24     56
2  Charlie   27     78
3    David   38     82
      Name  Age  Score  salary
0    Alice   23     34    2000
1      Bob   24     56    4000
2  Charlie   27     78    3007
3    David   38     82    2990


In [101]:
df = pd.DataFrame({'A' : [2,3],'B': [4,6]})

df.loc[len(df)] = [5,6]

print(df)

# ab = df.drop('B', axis=1)
# print(ab)

# ab = df.drop('A', axis=1, inplace=True)
# print(ab)

filtered =df.drop(1,axis=0)
print(filtered)


   A  B
0  2  4
1  3  6
2  5  6
   A  B
0  2  4
2  5  6


read csv files

In [102]:
df = pd.read_csv('employees.csv')
print(df)

   emploeeId     name department  salary
0          1    Jhone         IT   60000
1          2  sachini         HR  690900
2          3   sasoba    Finance   20000
3          4     dinu         IT   65000


In [1]:
import pandas as pd
df = pd.read_json('students.json')
print(df)

      name  grade
0    alice     85
1      bob     72
2  charlie     90
3    david     65
4  sachini     59
